version: "v1.0"
name: Using cmd_file.
semaphore_image: standard
blocks:
 - name: Calling external text file
   build:
      jobs:
        - name: Using command_file
          cmd_file: /home/runner/goDemo/command_file
      prologue:
          commands:
            - checkout
            - cd $SEMAPHORE_GIT_DIR
