version: "v1.0"
name: Using cmd_file.
semaphore_image: standard
blocks:
 - name: Calling text file
   build:
      jobs:
        - name: Using command_file
          cmd_file: command_file
      prologue:
          commands:
            - checkout
            - cd $SEMAPHORE_GIT_DIR
      epilogue:
          cmd_file: command_file

